package com.melnik.databaseTraining.controllers;

import com.melnik.databaseTraining.Student;
import com.melnik.databaseTraining.StudentStatus;
import com.melnik.databaseTraining.repo.StudentsRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

@RestController
@RequestMapping("/student")
public class StudentController {

    @Autowired
    private StudentsRepository studentsRepository;

    @GetMapping
    public List<Student> getAllOrByStatus(@RequestParam(required = false) StudentStatus status) {
        if (status == null) {
            return studentsRepository.findAll();
        }
        return studentsRepository.list(status);
    }

    @GetMapping("/{id}")
    public Optional<Student> getByID(@PathVariable("id") long id) {
        return studentsRepository.findById(id);
    }


    // send JSON without ID param cause ID is autogenerated
    @PostMapping()
    public ResponseEntity add(@RequestBody Student student) {
        studentsRepository.save(student);
        return new ResponseEntity(HttpStatus.CREATED);
    }


    // send JSON without ID param cause ID is taken from the path
    @PutMapping("/{id}")
    public ResponseEntity edit(@PathVariable("id") long id, @RequestBody Student student) {
        if (!studentsRepository.existsById(id)) {
            return new ResponseEntity(HttpStatus.NOT_FOUND);
        } else {
            studentsRepository.update(id, student);
            return new ResponseEntity(HttpStatus.FOUND);
        }
    }

    @DeleteMapping("/{id}")
    public ResponseEntity delete(@PathVariable("id") long id) {
        if (studentsRepository.existsById(id)) {
            studentsRepository.deleteById(id);
            return new ResponseEntity(HttpStatus.FOUND);
        } else return new ResponseEntity(HttpStatus.NOT_FOUND);
    }

}

