version: '3.9'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 31667
      POSTGRES_DB: training
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d training"]
      interval: 30s
      start_period: 30s


  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/training
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 31667
    ports:
      - "8080:8080"
    healthcheck:
      test: curl --fail http://localhost:8080/healthcheck || exit 1
      interval: 60s
      start_period: 30s

volumes:
  postgres_data: